config/routes.rb
Memoapp::Application.routes.draw do

  get "contents/index"

  resources :contents
  resources :sessions
  resources :memos
  resources :tags
    
  # root
  root :to => 'contents#index'
  
  # OmniAuth
  match "/auth/:provider/callback" => "sessions#create"

  # ログアウト
  match "/logout" => "sessions#destroy", :as => :logout
  # 退会
  match "/remove" => "users#destroy", :as => :remove

  # 利用規約
  match "/rule" => "contents#rule", :as => :rule
  # ヘルプ
  match "/help" => "contents#help", :as => :help

  # 検索
  match 'memos/find'
  match "/tags_find" => "memos#tag_find", :as => :tags_find

  # もっと読む
  match "/load_more" => "memos#show_list", :as => :load_more
  match "/load_find_more" => "memos#find_list", :as => :load_find_more
  match "/load_tag_find_more" => "memos#tag_find_list", :as => :load_tag_find_more

  # タグ更新
  match "/tags_input" => "tags#input", :as => :tags_input
  match "/tags_show" => "tags#show", :as => :tags_show

  # メモ更新
  match 'memos/update'
  match "/memos_input" => "memos#input", :as => :memos_input
  match "/memos_show" => "memos#show", :as => :memos_show

  # メモ並び替え
  match 'memos/reorder' => 'memos#reorder', :via => [:get, :post]


end

app/controllers/contents_controller.rb
# coding: utf-8
class ContentsController < ApplicationController
  
  # index表示
  def index

    # ログイン中の場合
    if current_user
      # 初期化
      session_init
      
      # memo新規作成用
      @memo = Memo.new
     
      # ユーザーのmemoを取得
      @memos,@count_memos = get_memos

      # もっと読むボタンのリンク先
      @load_more_option = "show"

      respond_to do |format|
        format.html { render }
        format.json { render json: @memos }
        format.js
      end
    end
  end
  
  def rule
  end

  def help
  end

  
end

app/helpers/contents_helper.rb
module ContentsHelper


end

app/views/contents/_tagupdate.html.erb
<div class="text-right" id="tag<%= @memo_id %>">
  <% @tags.each do |tag| %>
    <a href="#"><%= tag.name %></a> 
  <% end %>
  <%= link_to '<i class="icon-edit"></i> '.html_safe, tag_update_path(:memo_id => @memo_id) , :remote => true %>
</div>

app/views/contents/create.js.erb
$('#posts').prepend("<%= escape_javascript(render :partial => @memos)%>");
$('#memo_text').val('');

app/views/contents/error.js.erb
showErrorToast("<%= @error_comment %>");

app/views/contents/help.html.erb
<div class="row">
  <div class="span10 offset1">

<h3>ヘルプ</h3>
<dl>
  <dt>1.ユーザー</dt>
  <dd>
    <ul>
      <li>登録</li>
        <ul>
          <li>TwitterのOAuth認証を利用してユーザー登録を行っています。TwitterとMyFragmentsの連携を認証することでユーザー登録できます。</li>
        </ul>
      <li>退会</li>
        <ul>
          <li>ユーザーメニューから退会を選ぶことでユーザーを削除できます。</li>
          <li>退会と同時に登録されたメモも削除します。削除したデータは復元できません。</li>
        </ul>
      <li>ログイン</li>
        <ul>
          <li>TwitterとMyFragmentsの連携を認証することでログインできます。</li>
        </ul>
      <li>ログアウト</li>
        <ul>
          <li>一定期間が経つとで自動でログアウトします。再度ログインしてください。</li>
          <li>手動でログアウトする場合は、ユーザーメニューからログアウトを選んでください。</li>
        </ul>
    </ul>
  </dd>

  <dt>2.メモ</dt>
  <dd>
    <ul>
      <li>投稿</li>
        <ul>
          <li>右上のテキストエリアに入力して鉛筆ボタンをクリックしてください。</li>
          <li>最大256字まで投稿できます。</li>
          <li>空白での投稿はできません。</li>
          <li>1つのメモにつき、タグを16個まで設定することができます。</li>
        </ul>
      <li>編集</li>
        <ul>
          <li>編集ボタンをクリックすることで編集できます。</li>
        </ul>
      <li>削除</li>
        <ul>
          <li>ゴミ箱ボタンをクリックすることで削除できます。削除したメモは復元できません。
        </ul>
      <li>並べ替え</li>
        <ul>
          <li>移動ボタンをドラッグ＆ドロップすることで任意の順番に並べ替えることができます。</li>
        </ul>
    </ul>
  </dd>


  <dt>3.タグ</dt>
  <dd>
    <ul>
      <li>設定</li>
        <ul>
          <li>メモを登録する時に、テキストエリアの下の入力欄にタグを入力することで設定できます。</li>
          <li>空白で区切ることで、複数のタグを設定することができます。</li>
          <li>1つのメモにつき、最大16個まで登録できます。</li>
          <li>1つのメモにつき、最大128文字まで登録できます。</li>
        </ul>
      <li>編集</li>
        <ul>
          <li>タグアイコンをクリックすることで編集できます。</li>
        </ul>
    </ul>
  </dd>
  
  <dt>4.検索</dt>
  <dd>
    <ul>
      <li>文字列検索</li>
        <ul>
          <li>左側の入力欄に検索したい文字列入力して検索ボタンをクリックしてください。</li>
          <li>空白で区切ることで、AND検索が行えます。</li>
          <li>検索対象はメモとタグ両方です。</li>
        </ul>
      <li>タグ検索</li>
        <ul>
          <li>タグのリンクをクリックすることで、同じタグがついたメモを検索できます。</li>
        </ul>
    </ul>
  </dd>

</dl>


  </div>
</div>

app/views/contents/index.html.erb
<% if current_user %>

    <div class="row">
      <div class="span3">
        <%= form_for @memo, :url => {:controller => 'memos',:action => 'create'}, :remote => true do |f| %>
          <%= f.text_area :text, :class => "span3", :size=>"10x3" %>
          <%= f.text_field :tag_name, :class => "span3" %>
          <%= button_tag(:type => 'submit', :class => 'btn btn-primary') do %>
            <i class="icon-pencil icon-white"></i>
          <% end %>
        <% end %>
      
        <hr>
        <%= form_tag(:controller => "memos", :action => "find") do %>
          <%= text_field_tag 'search_string', nil, :class => 'span3' %>
          <%= button_tag(:type => 'submit', :class => 'btn btn-primary') do %>
            <i class="icon-search icon-white"></i>
          <% end %>
        <% end %>

        <hr>

      </div><!-- /span3 -->

      <div class="span9">

        <div id="error">
        </div>

        <div id="posts">
          <%= render @memos %>
        </div>
        
        <% if @count_memos == 0 %>
          
        <% else %>
          <% if @load_more_option == "show" %>
            <%= link_to load_more_path , :remote => true, :id => "load_more_link" do %>
              <button class="btn" type="button"><i class="icon-arrow-down"></i></button>
            <% end %>
          <% elsif @load_more_option == "find" %>
            <%= link_to load_find_more_path , :remote => true, :id => "load_more_link" do %>
              <button class="btn" type="button"><i class="icon-arrow-down"></i></button>
            <% end %>
          <% elsif @load_more_option == "tag_find" %>
            <%= link_to load_tag_find_more_path , :remote => true, :id => "load_more_link" do %>
              <button class="btn" type="button"><i class="icon-arrow-down"></i></button>
            <% end %>
          <% end %>
        <% end %>
          
      </div><!-- /span9 -->
    </div><!-- /row -->


<script type="text/javascript">

$(function(){
  $('#posts').sortable({
    cursor: 'move',
    handle: 'span',
    placeholder: 'placeholder',
    forcePlaceholderSize: true,
    opacity: 0.4,
    update: function() {
      $.ajax({
        url: '/memos/reorder',
        type: 'POST',
        dataType: 'text',
        data: $(this).sortable('serialize'),
      }).done( )
        .fail( function(){showErrorToast("並べ替えに失敗しました。<br>リロードしてください。");} );
    }
  });
});

</script>

<% else %>

<div class="hero-unit">
  <%= image_tag("logo-large.png") %>
    <p class="login_comment">気軽にメモして、整理は後で。どんどんメモする自分だけのメモ帳です。</p>
    <p class="weak login_button" >
      <%= link_to image_tag('sign-in-with-twitter-gray.png'),"/auth/twitter" %>　Twitterアカウントを使ってログインします。
    </p>
</div>

<% end %>


<% unless flash[:notice].blank? %>
  <script type="text/javascript" charset="utf-8">
    $(function(){
      $().toastmessage('showNoticeToast', "<%= flash[:notice] %>");
    });
  </script>
<% end %>

<% unless flash[:alert].blank? %>
  <script type="text/javascript" charset="utf-8">
    $(function(){
      $().toastmessage('showErrorToast', "<%= flash[:alert] %>");
    });
  </script>
<% end %>

app/views/contents/index.js.erb
$('#posts').append("<%= escape_javascript(render :partial => @memos)%>");
<% if @count_memos == 0 %>
  $('#load_more_link').hide();
<% end %>

app/views/contents/rule.html.erb
<div class="row">
  <div class="span10 offset1">

<h3>MyFragments利用規約</h3>
<dl>
  <dt>1.利用規約について</dt>
  <dd>
    <ul>
      <li>kanorimon（以下「運営者」といいます。）が管理、運営するWebサービス「MyFragments」（以下「本サービス」といいます。）の利用について、以下のとおり「MyFragments利用規約」（いか「本規約」といいます。）を定めます。 </li>
      <li>利用者が本規約を確認したか否かを問わず、本サービスの利用を開始した時点で、本規約に同意したものとします。</li>
      <li>本規約の変更通知について、本サービス上に掲載することにより、利用者に通知したものとします。また、その掲載した時点で効力を発するものとします。</li>
    </ul>
  </dd>

  <dt>2.本サービスについて</dt>
  <dd>
    <ul>
      <li>本サービスの利用料金は、無料とします。</li>
      <li>本サービスは、予告なくメンテナンスを実施することがあります。</li>
      <li>本サービスは、予告なくサービスを終了することがあります。</li>
    </ul>
  </dd>

  <dt>3.免責事項</dt>
  <dd>
    <ul>
      <li>本サービスは、以下の内容について一切の保証を行うものではありません。</li>
        <ul>
          <li>サービス内容が利用者の要求に合致すること。</li>
          <li>サービスが中断されないこと。</li>
          <li>サービスにおいていかなるエラーや不具合または障害が発生しないこと。</li>
          <li>サービスにいかなる内容の不備、誤り等がないこと。</li>
          <li>利用者が登録したデータが保管されること。</li>
          <li>利用者の機器及びソフトウェアの動作。</li>
        </ul>
      <li>運営者は、利用者の損害について、一切責任を負わないものとします。</li>
      <li>運営者は、利用者の承諾なく、又は利用者への事前の通知を行うことなく、任意に本サービスの全体若しくは一部を変更し、又は一時中断し、停止し、若しくは終了することがあります。この場合も、運営者は、利用者に対していかなる責任も負わないものとします。</li>
    </ul>
  </dd>

  <dt>4.禁止行為</dt>
  <dd>
    <ul>
      <li>本サービスを、非合法な目的で利用することを禁止します。</li>
      <li>本サービスを利用するに当たり、以下に該当し、又はその恐れのある行為を禁止します。</li>
        <ul>
          <li>本サービス又は本サービスに接続しているサーバー若しくはネットワークを妨害したり、混乱させたりすること。</li>
          <li>故意又は過失を問わず法令に違背する行為。</li>
        </ul>
      <li>運営者が承認した場合を除き、利用者は、本サービス、本サービスの利用（使用）又は本サービスへの接続について全部又は一部を問わず、転売し、又は転用することを禁止します。</li>
    </ul>
  </dd>

  <dt>5.プライバシーについて</dt>
  <dd>
    <ul>
      <li>運営者は、個人のプライバシー、名誉その他第三者の権利を侵害することのないよう、利用者に関する情報の取扱いに十分、配慮します。</li>
    </ul>
  </dd>

</dl>

  </div>
</div>