config/routes.rb
Memoapp::Application.routes.draw do

  get "contents/index"

  resources :contents
  resources :sessions
  resources :memos
  resources :tags
    
  # root
  root :to => 'contents#index'
  
  # OmniAuth
  match "/auth/:provider/callback" => "sessions#create"

  # ログアウト
  match "/logout" => "sessions#destroy", :as => :logout
  # 退会
  match "/remove" => "users#destroy", :as => :remove

  # 利用規約
  match "/rule" => "contents#rule", :as => :rule
  # ヘルプ
  match "/help" => "contents#help", :as => :help

  # 検索
  match 'memos/find'
  match "/tags_find" => "memos#tag_find", :as => :tags_find

  # もっと読む
  match "/load_more" => "memos#show_list", :as => :load_more
  match "/load_find_more" => "memos#find_list", :as => :load_find_more
  match "/load_tag_find_more" => "memos#tag_find_list", :as => :load_tag_find_more

  # タグ更新
  match "/tags_input" => "tags#input", :as => :tags_input
  match "/tags_show" => "tags#show", :as => :tags_show

  # メモ更新
  match 'memos/update'
  match "/memos_input" => "memos#input", :as => :memos_input
  match "/memos_show" => "memos#show", :as => :memos_show

  # メモ並び替え
  match 'memos/reorder' => 'memos#reorder', :via => [:get, :post]


end

app/models/tag.rb
# coding: utf-8
class Tag < ActiveRecord::Base
  # データ定義
  attr_accessible :memo_id, :name
  # リレーション
  belongs_to :memo
end

app/controllers/tags_controller.rb
# coding: utf-8
class TagsController < ApplicationController

  # タグ表示
  def show
    # 画面制御用memo_id
    @memo_id = params[:memo_id]    
    # タグ取得
    @tags = Tag.where('memo_id = ?',params[:memo_id])
    render 'tags/show.js.erb'
  end

  # タグ入力表示
  def input
    # 画面制御用memo_id
    @memo_id = params[:memo_id]
    @tags = Tag.where('memo_id = ?', params[:memo_id])

    # 入力用タグ文字列設定
    @print_tag = ""
    @tags.each{|tag|
      @print_tag = @print_tag.concat(tag.name).concat(" ")
    }

    render 'tags/input.js.erb'
    
  end

  # タグ登録
  def create
    begin
      # 画面制御用memo_id
      @memo_id = params[:memo_id]

      # デフォルトエラーコメント設定
      @error_comment = ERROR_COMMENT

      # 入力値の検証
      if !(validate_tag(params[:tag_names]).blank?)
        @error_comment = validate_tag(params[:tag_names])
        raise
      end
      
      # タグ削除
      delete_tags(params[:memo_id])

      # タグを登録
      create_tags(params[:tag_names],params[:memo_id])
      
      # 表示用タグの取得
      @tags = Tag.where('memo_id = ?',params[:memo_id])
    rescue
      render 'contents/error.js.erb'

    else
      render 'tags/show.js.erb'
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_input.html.erb
<div class="text-right" id="tag_<%= @memo_id %>">
  <%= form_tag({:controller => "tags", :action => "create"}, {:class => "form-inline",:remote => true}) do %>
    <%= hidden_field_tag 'memo_id', @memo_id %>
    <%= text_field_tag 'tag_names', nil, :class => 'span6', :value => @print_tag %>
    <%= button_tag(:type => 'submit', :class => 'btn btn-primary') do %>
      <i class="icon-pencil icon-white"></i>
    <% end %>
    <%= link_to tags_show_path(:memo_id => @memo_id) , :remote => true do %>
      <i class="icon-remove"></i>
    <% end %>
  <% end %>
</div>

app/views/tags/_show.html.erb
<div class="text-right" id="tag_<%= @memo_id %>">
  <% @tags.each do |tag| %>
    <a href="#"><%= tag.name %></a>&nbsp;
  <% end %>
  <%= link_to '<i class="icon-tags"></i> '.html_safe, tags_input_path(:memo_id => @memo_id) , :remote => true %>
</div>

app/views/tags/input.js.erb
$('#tag_<%= @memo_id %>').replaceWith("<%= escape_javascript(render :partial => 'tags/input', :locals => {:memo_id => @memo_id, :print_tag => @print_tag} )%>");

app/views/tags/show.js.erb
$('#tag_<%= @memo_id %>').replaceWith("<%= escape_javascript(render :partial => 'tags/show', :locals => {:memo_id => @memo_id, :tags => @tags} )%>");