config/routes.rb
Memoapp::Application.routes.draw do

  get "contents/index"

  resources :contents
  resources :sessions
  resources :memos
  resources :tags
    
  # root
  root :to => 'contents#index'
  
  # OmniAuth
  match "/auth/:provider/callback" => "sessions#create"

  # ログアウト
  match "/logout" => "sessions#destroy", :as => :logout
  # 退会
  match "/remove" => "users#destroy", :as => :remove

  # 利用規約
  match "/rule" => "contents#rule", :as => :rule
  # ヘルプ
  match "/help" => "contents#help", :as => :help

  # 検索
  match 'memos/find'
  match "/tags_find" => "memos#tag_find", :as => :tags_find

  # もっと読む
  match "/load_more" => "memos#show_list", :as => :load_more
  match "/load_find_more" => "memos#find_list", :as => :load_find_more
  match "/load_tag_find_more" => "memos#tag_find_list", :as => :load_tag_find_more

  # タグ更新
  match "/tags_input" => "tags#input", :as => :tags_input
  match "/tags_show" => "tags#show", :as => :tags_show

  # メモ更新
  match 'memos/update'
  match "/memos_input" => "memos#input", :as => :memos_input
  match "/memos_show" => "memos#show", :as => :memos_show

  # メモ並び替え
  match 'memos/reorder' => 'memos#reorder', :via => [:get, :post]


end

app/models/memo.rb
# coding: utf-8
class Memo < ActiveRecord::Base
  # データ定義
  attr_accessible :text, :user_id, :tweet_flg, :tag_name, :seq
  # dbに存在しない項目の定義
  attr_accessor :tweet_flg, :tag_name
  # リレーション
  belongs_to :user
  has_many :tags, :dependent => :destroy

  validates :text, 
    :presence => true,
    :length => {:maximum => 256}

  validates :seq, :uniqueness => true
  
  # 一回あたりのメモ取得最大数
  MAX_NUM = 15

  # メモ取得時のconditions作成
  def self.get_conditions(user_id,last_memo_seq)
    @condition = []
    @condition.push([" user_id = ? ",user_id]) if user_id
    @condition.push([" seq < ? ",last_memo_seq]) if last_memo_seq

    @condition = self.flatten_conditions(@condition)
    logger.debug(@condition)     

    return @condition
  end
  
  # メモ取得
  def self.find_memos(condition)
    @memos = Memo.find(:all,:order => "seq DESC",:limit => MAX_NUM,:conditions => condition)
    return @memos
  end

  # 残メモ数取得
  def self.count_memos(condition)
    @count_memos = Memo.count(:conditions => condition)
    return @count_memos
  end

  # メモ取得時のconditions作成（タグ結合）
  def self.get_conditions_with_tags(user_id,last_memo_seq,search_strings,tag_search_string)
    @condition = []
    @condition.push([" memos.user_id = ? ",user_id]) if user_id
    @condition.push([" memos.seq < ? ",last_memo_seq]) if last_memo_seq

    unless search_strings.blank?
      search_string =  search_strings.gsub(/　/," ").split(nil)
      search_string.each do |s|
        @condition.push([" memos.text like ? or tags.name like ? ",'%' + s + '%','%' + s + '%']) if s
      end
    end

    @condition.push([" tags.name = ? ",tag_search_string]) if tag_search_string

    @condition = self.flatten_conditions(@condition)
    logger.debug(@condition)

    return @condition
  end
  
  # メモ取得（タグ結合）
  def self.find_memos_with_tags(condition)
    @memos_id = Memo.find(:all,:order => "memos.seq DESC",:limit => MAX_NUM,:conditions => condition,:include => :tags, :select => "memos.id")
    @memos = Memo.where(["id in (?)", @memos_id]).order("seq DESC")
    return @memos
  end

  # 残メモ数取得（タグ結合）
  def self.count_memos_with_tags(condition)
    @count_memos = Memo.count(:conditions => condition,:include => :tags)
    return @count_memos
  end
  
  # 検索条件の作成
  def self.flatten_conditions(conditions)
    return nil if conditions.empty?
    ps = []
    condition = conditions.collect do |c|
      next if c.size < 1
      ps += c[1..(c.size)]
      "( #{c[0]} )"
    end.delete_if { |c| c.blank? }.join(" #{"and"} ")
    [condition, ps].flatten unless condition.empty?
  end
  
  # 初回メモ登録
  def self.new_user(user_id)
    texts = []
    texts[0] = "MyFragmentsへようこそ！

メモの右側にあるメニューで編集、削除、ドラッグ＆ドロップでの並べ替えができます。
メモにタグをつけて管理することもできます。
詳しい使い方はヘルプをご覧ください！"

    tags = []
    tags[0] = []
    tags[0][0] = "システムメッセージ"
    
    texts.each_with_index do |text,i|
      @first_memos = Memo.new
      @first_memos.user_id = user_id
      @first_memos.text = text
      # dbに保存
      @first_memos.save!

      # シーケンス番号を設定
      @first_memos.seq =  @first_memos.id
      @first_memos.save!

        tags[i].each_with_index do |tag,k|
          @first_tags = Tag.new
          @first_tags.memo_id = @first_memos.id
          @first_tags.name = tag
          # dbに保存
          @first_tags.save!
      end
    end
  end
  
end

app/controllers/memos_controller.rb
# coding: utf-8
class MemosController < ApplicationController
  protect_from_forgery :except => ["reorder"]

  # メモ一覧（もっと読む）
  def show_list
    # ユーザーのmemoを取得
    @memos,@count_memos = get_memos
    # 画面表示
    render 'contents/index.js.erb'
  end
  
  # 文字列検索
  def find
    # 初期化
    session_init
    # memo新規作成用
    @memo = Memo.new
    # 検索文字列をsessionに設定
    session[:search_string] = params[:search_string]
    # メモ検索
    @memos,@count_memos = search_memos
    # もっと読むボタンのリンク先
    @load_more_option = "find"
    # 画面表示
    render 'contents/index.html.erb'
  end

  # 文字列検索（もっと読む）
  def find_list
    # メモ検索
    @memos,@count_memos = search_memos
    # 画面表示
    render 'contents/index.js.erb'
  end

  # タグ検索
  def tag_find
    # 初期化
    session_init
    # memo新規作成用
    @memo = Memo.new
    # 検索文字列をsessionに設定
    session[:tag_search_string] = params[:tag_name]
    # メモ検索
    @memos,@count_memos = search_memos
    # もっと読むボタンのリンク先
    @load_more_option = "tag_find"
    # 画面表示
    render 'contents/index.html.erb'
  end
  
  # タグ検索（もっと読む）
  def tag_find_list
    # メモ検索
    @memos,@count_memos = search_memos
    # 画面表示
    render 'contents/index.js.erb'
  end
  
  # ajaxによる並べ替え
  def reorder
    
    begin
      # デフォルトエラーコメント設定
      @error_comment = ERROR_COMMENT
      logger.debug(session[:before_seq])
      logger.debug(session[:before_id])

      @memo_ids = params[:memo]
  
      session[:before_seq].sort!.reverse!
    
      Memo.transaction do
     
        @target_memoids =[]

        @memo_ids.each_with_index do |ids,i|
          if ids != session[:before_id][i]
        
            @target_memo = Memo.find(ids)
            @target_memo.seq = session[:before_seq][i].to_i * -1
            @target_memo.save!

            @target_memoids.push(@target_memo.id)

            session[:before_id][i] = ids

          end
        end

         #テスト用エラー発生
        #logger.debug(session[:before_id][i])

        @target_memoids.each do |ids|
          @memo = Memo.find(ids)
          @memo.seq = @memo.seq * -1
          @memo.save!
        end
        
      end
    rescue

    else
      render :nothing => true

    end
  
  end


  # メモ新規作成
  def create
    begin
      # デフォルトエラーコメント設定
      @error_comment = ERROR_COMMENT
      # 入力値の検証
      if !(validate_memo(params[:memo][:text]).blank?)
        @error_comment = validate_memo(params[:memo][:text])
        raise
      end
      if !(validate_tag(params[:memo][:tag_name]).blank?)
        @error_comment = validate_tag(params[:memo][:tag_name])
        raise
      end
      
      # メモを登録
      @memo = memo_save_with_seq(params[:memo][:text])

      # タグを登録
      create_tags(params[:memo][:tag_name],@memo.id)

      # 表示用メモの取得
      @memos = Memo.find_by_id(@memo.id)
      
      # 画面に表示されているseqに追加
      session[:before_id].unshift(@memo.id)
      session[:before_seq].unshift(@memo.seq)
      
    rescue
      render 'contents/error.js.erb'

    else
      render 'memos/create.js.erb'
    end
  end
  
  
  # メモ登録
  def memo_save_with_seq(text)
    # メモの入力内容を設定
    @memo = Memo.new
    @memo.user_id = current_user.id
    @memo.text = text

    # dbに保存
    @memo.save!

    # シーケンス番号を設定
    @memo.seq = @memo.id
    @memo.save!
    
    return @memo
  end
  
  # メモ削除
  def destroy

    @delete_memo_id = params[:id]
    
    @memo = Memo.find(params[:id])

    # 画面に表示されているseqを削除
    session[:before_id].delete(@memo.id)
    session[:before_id].delete(@memo.id.to_s)
    session[:before_seq].delete(@memo.seq)
    session[:before_seq].delete(@memo.seq.to_s)

    @memo.destroy
    
    # ajax
    render 'memos/delete.js.erb'
  end
  
    # メモ表示
  def show
    # 画面制御用memo_id
    @memo_id = params[:memo_id]
    # タグ取得
    @memo_text = Memo.find(params[:memo_id]).text
    render 'memos/show.js.erb'
  end

  # メモ入力表示
  def input
    # 画面制御用memo_id
    @memo_id = params[:memo_id]
    @memo_text = Memo.find(params[:memo_id]).text

    render 'memos/input.js.erb'
    
  end
  
  
  # メモ更新
  def update
    begin
      # 画面制御用memo_id
      @memo_id = params[:memo_id]
      @memo_text = params[:memo_text]

      # デフォルトエラーコメント設定
      @error_comment = ERROR_COMMENT

      # 入力値の検証
      if !(validate_memo(params[:memo_text]).blank?)
        @error_comment = validate_memo(params[:memo_text])
        raise
      end

      # メモを更新
      @memo = Memo.find(params[:memo_id])
      @memo.text = params[:memo_text]
      @memo.save!
      
    rescue
      render 'contents/error.js.erb'

    else
      render 'memos/show.js.erb'
    end
  end
  
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_input.html.erb
<div class="span7" id="text_<%= @memo_id %>">
  <%= form_tag({:controller => "memos", :action => "update"}, {:class => "form-inline",:remote => true}) do %>
    <%= hidden_field_tag 'memo_id', @memo_id %>
    <%= text_area_tag 'memo_text', @memo_text, :class => 'span6' %>
    <%= button_tag(:type => 'submit', :class => 'btn btn-primary') do %>
      <i class="icon-pencil icon-white"></i>
    <% end %>
  <% end %>
</div>

app/views/memos/_memo.html.erb
      <div id="memo_<%= memo.id %>" name="memo_<%= memo.seq %>">
        <div class="row">
          <div class="span7" id="text_<%= memo.id %>">
            <%= br(memo.text) %>
          </div>
          <div class="span2">
            <div class="text-right">
              <% update_memo_id = "update_" + memo.id.to_s %>
              <%= link_to memos_input_path(:memo_id => memo.id), :remote => true, class: "btn btn-mini", :id => update_memo_id do %>
                <i class="icon-edit"></i>
              <% end %>
              <% update_close_memo_id = "update_close_" + memo.id.to_s %>
              <%= link_to memos_show_path(:memo_id => memo.id) , :remote => true, class: "btn btn-mini", :id => update_close_memo_id do %>
                <i class="icon-remove"></i>
              <% end %>
              <% delete_memo_id = "delete_" + memo.id.to_s %>
              <%= link_to memo, method: :delete, :remote => true, class: "btn btn-mini", :id => delete_memo_id, :confirm => "削除しますか？" do %>
                <i class="icon-trash"></i>
              <% end %>

              <span class="btn btn-mini" id="move_<%= memo.id %>" type="button"><i class="icon-move"></i></span>
            </div>
          </div>
        </div>

        <div class="row row-under">
          <div class="span7 weak">
            <div class="text-right" id="tag_<%= memo.id %>">
              <% memo.tags.each do |tag| %>
                <%= link_to tag.name, tags_find_path(:tag_name => tag.name) %>&nbsp;
              <% end %>
              <%= link_to '<i class="icon-tags"></i>'.html_safe, tags_input_path(:memo_id => memo.id) , :remote => true %>
            </div>
          </div>
          <div class="span2 weak">
            <div class="text-right">
              <%= memo.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
            </div>
          </div>
        </div>

        <hr class="memo">


<script type="text/javascript">
$(function(){
  $('#update_close_<%= memo.id.to_s %>').hide();
});
</script>

      </div>

app/views/memos/_show.html.erb
<div class="span7" id="text_<%= @memo_id %>">
  <%= br(@memo_text) %>
</div>

app/views/memos/create.js.erb
$('#posts').prepend("<%= escape_javascript(render :partial => @memos)%>");
$('#memo_text').val('');
$('#memo_tag_name').val('');

app/views/memos/delete.js.erb
$("#memo_<%= @delete_memo_id %>").remove();

app/views/memos/input.js.erb
$('#update_<%= @memo_id %>').hide();
$('#update_close_<%= @memo_id %>').show();
$('#text_<%= @memo_id %>').replaceWith("<%= escape_javascript(render :partial => 'memos/input', :locals => {:memo_id => @memo_id, :memo_text => @memo_text} )%>");

app/views/memos/show.js.erb
$('#update_<%= @memo_id %>').show();
$('#update_close_<%= @memo_id %>').hide();
$('#text_<%= @memo_id %>').replaceWith("<%= escape_javascript(render :partial => 'memos/show', :locals => {:memo_id => @memo_id, :memo_text => @memo_text} )%>");