config/routes.rb
Memoapp::Application.routes.draw do

  get "contents/index"

  resources :contents
  resources :sessions
  resources :memos
  resources :tags
    
  # root
  root :to => 'contents#index'
  
  # OmniAuth
  match "/auth/:provider/callback" => "sessions#create"

  # ログアウト
  match "/logout" => "sessions#destroy", :as => :logout
  # 退会
  match "/remove" => "users#destroy", :as => :remove

  # 利用規約
  match "/rule" => "contents#rule", :as => :rule
  # ヘルプ
  match "/help" => "contents#help", :as => :help

  # 検索
  match 'memos/find'
  match "/tags_find" => "memos#tag_find", :as => :tags_find

  # もっと読む
  match "/load_more" => "memos#show_list", :as => :load_more
  match "/load_find_more" => "memos#find_list", :as => :load_find_more
  match "/load_tag_find_more" => "memos#tag_find_list", :as => :load_tag_find_more

  # タグ更新
  match "/tags_input" => "tags#input", :as => :tags_input
  match "/tags_show" => "tags#show", :as => :tags_show

  # メモ更新
  match 'memos/update'
  match "/memos_input" => "memos#input", :as => :memos_input
  match "/memos_show" => "memos#show", :as => :memos_show

  # メモ並び替え
  match 'memos/reorder' => 'memos#reorder', :via => [:get, :post]


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MyFragments</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>
  <body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <% if current_user %>
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% end %>
        <a class="brand" href="<%= root_url(:only_path => false) %>"><%= image_tag("logo-small.png") %></a>

        <% if current_user %>
        <div class="nav-collapse collapse">
          <div class="navbar-form pull-right">
            <span class="btn-group">
              <%= image_tag current_user.avatar.url , :class => "img-rounded my-icon" %>
              <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.nickname %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu pull-right">
                <li><%= link_to "ログアウト" ,logout_path %></li>
                <li class="divider"></li>
                <li><%= link_to "退会", "#", "data-toggle" => "modal", "data-target" => "#remove_user" %></li>
              </ul>
            </span>
          </div>
        </div><!--/.nav-collapse -->
        <% end %>

      </div><!--/.container -->
    </div><!--/.navbar-inner -->
  </div><!--/.navbar -->

<div class="modal hide" id="remove_user">
  <div class="modal-body">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <p>メモはすべて削除されます。退会しますか？</p>
  </div>
  <div class="modal-footer">
    <%= link_to "OK", remove_path, class: 'btn btn-danger' %>
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
  </div>
</div>


  <div class="container">

    <%= yield %>

    <hr>
    
    <footer>
      <div>
        <%= link_to "ヘルプ", help_path %> | 
        <%= link_to "利用規約", rule_path %> | 
        <a href="http://twitter.com/kanorimon" target="_blank" >お問い合わせ</a>
      </div>
    </footer>

  </div> <!-- /container -->

  </body>
</html>